services:
  dogtracker-backend:
    build: .
    container_name: dogtracker
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DEBUG=true
    restart: unless-stopped
    networks:
      - dogtracker-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    env_file:
      - mqtt.env
      - prod.env

  dogtracker-admin:
    build: ./admin_website
    container_name: dogtracker-admin
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # For hot reload in Docker
    networks:
      - dogtracker-net
    depends_on:
      - dogtracker-backend


networks:
  dogtracker-net:
    external: true

